config/routes.rb
RspecDemo::Application.routes.draw do
  resources :colleagues

   root :to => 'colleagues#index'

end

app/models/colleague.rb
class Colleague < ActiveRecord::Base



   def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colleagues_controller.rb
class ColleaguesController < ApplicationController
  # GET /colleagues
  # GET /colleagues.json
  def index
    @colleagues = Colleague.all

    respond_to do |format|
      format.html # index.html.erb
      
      format.json { render json: @colleagues }
    
      format.csv { send_data Colleague.to_csv }
      format.xls { send_data Colleague.to_csv(col_sep: "\t") }

    end
  end

  # GET /colleagues/1
  # GET /colleagues/1.json
  def show
    @colleague = Colleague.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @colleague }
    end
  end

  # GET /colleagues/new
  # GET /colleagues/new.json
  def new
    @colleague = Colleague.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @colleague }
    end
  end

  # GET /colleagues/1/edit
  def edit
    @colleague = Colleague.find(params[:id])
  end

  # POST /colleagues
  # POST /colleagues.json
  def create
    @colleague = Colleague.new(params[:colleague])

    respond_to do |format|
      if @colleague.save
        format.html { redirect_to @colleague, notice: 'Colleague was successfully created.' }
        format.json { render json: @colleague, status: :created, location: @colleague }
      else
        format.html { render action: "new" }
        format.json { render json: @colleague.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colleagues/1
  # PUT /colleagues/1.json
  def update
    @colleague = Colleague.find(params[:id])

    respond_to do |format|
      if @colleague.update_attributes(params[:colleague])
        format.html { redirect_to @colleague, notice: 'Colleague was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @colleague.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleagues/1
  # DELETE /colleagues/1.json
  def destroy
    @colleague = Colleague.find(params[:id])
    @colleague.destroy

    respond_to do |format|
      format.html { redirect_to colleagues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleagues_helper.rb
module ColleaguesHelper
end

app/views/colleagues/_form.html.erb
<%= form_for(@colleague) do |f| %>
  <% if @colleague.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colleague.errors.count, "error") %> prohibited this colleague from being saved:</h2>

      <ul>
      <% @colleague.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleagues/edit.html.erb
<h1>Editing colleague</h1>

<%= render 'form' %>

<%= link_to 'Show', @colleague %> |
<%= link_to 'Back', colleagues_path %>

app/views/colleagues/index.html.erb
<a href=# class="colorbox">
  <%= image_tag("flower.png", :size => "60x60",:alt => "odc decoration") %>
</a>

<h1>Listing colleagues</h1>
<%= link_to 'Export', colleagues_path(request.parameters.merge({:format => :xls})) %>

 <%= link_to "CSV", colleagues_path(format: "csv") %> |
  <%= link_to "Excel", colleagues_path(format: "xls") %>

  <%= link_to 'Create a new company',
         new_colleague_path, 
        :onclick=>"window.open(this.href,'create_colleague', 'height=600, width=600');return false;" 
%>


<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Middle name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colleagues.each do |colleague| %>
  <tr>
    <td><%= colleague.first_name %></td>
    <td><%= colleague.last_name %></td>
    <td><%= colleague.middle_name %></td>
    <td><%= link_to 'Show', colleague %></td>
    <td><%= link_to 'Edit', edit_colleague_path(colleague) %></td>
    <td><%= link_to 'Destroy', colleague, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Colleague', new_colleague_path %>

app/views/colleagues/index.xls.erb
<a href="<%= idea_post.photo.url %>" class="colorbox">
  <%= image_tag idea_post.photo.url(:thumb), :class => 'photo' %>
</a>

<table border="1">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.id %></td>
    <td><%= product.name %></td>
    <td><%= product.released_on %></td>
    <td><%= product.price %></td>
  </tr>
  <% end %>
</table>

app/views/colleagues/new.html.erb
<h1>New colleague</h1>

<%= render 'form' %>

<%= link_to 'Back', colleagues_path %>

app/views/colleagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @colleague.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @colleague.last_name %>
</p>

<p>
  <b>Middle name:</b>
  <%= @colleague.middle_name %>
</p>


<%= link_to 'Edit', edit_colleague_path(@colleague) %> |
<%= link_to 'Back', colleagues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RspecDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>